import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    slug: "xiaomi-g27i-27-monitor",
    name: 'Монитор 27" Xiaomi G27i',
    category: "monitors",
    subcategory: "gaming-monitors",
    brand: "Xiaomi",
    model: "G27i",
    sku: "XM-G27I-001",
    price: 16990,
    oldPrice: 19990,
    discount: 15,
    cashback: 850,
    stock: 15,
    rating: 4.7,
    reviewCount: 23,
    description:
      "Xiaomi G27i - игровой монитор с диагональю 27 дюймов, разрешением Full HD (1920x1080), частотой обновления 165 Гц и временем отклика 1 мс. Монитор оснащен матрицей IPS, имеет яркость 300 кд/м² и контрастность 1000:1. Поддерживает технологии AMD FreeSync Premium и HDR10.",
    shortDescription:
      "Игровой монитор с частотой 165 Гц и временем отклика 1 мс",
    specifications: [
      { name: "Диагональ", value: '27"' },
      { name: "Разрешение", value: "1920x1080 (Full HD)" },
      { name: "Тип матрицы", value: "IPS" },
      { name: "Частота обновления", value: "165 Гц" },
      { name: "Время отклика", value: "1 мс" },
      { name: "Яркость", value: "300 кд/м²" },
      { name: "Контрастность", value: "1000:1" },
      { name: "Интерфейсы", value: "HDMI 2.0, DisplayPort 1.4, 3.5 мм аудио" },
      { name: "Особенности", value: "AMD FreeSync Premium, HDR10" },
    ],
    images: [
      {
        id: "1-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Xiaomi G27i - вид спереди",
        isPrimary: true,
      },
      {
        id: "1-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Xiaomi G27i - вид сзади",
        isPrimary: false,
      },
      {
        id: "1-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Xiaomi G27i - интерфейсы",
        isPrimary: false,
      },
    ],
    features: [
      "Высокая частота обновления 165 Гц",
      "Быстрое время отклика 1 мс",
      "Технология AMD FreeSync Premium",
      "Поддержка HDR10",
      "Регулировка наклона и высоты",
    ],
    isRecommended: true,
  },
  {
    id: "2",
    slug: "asus-dual-rx7800xt-o16g",
    name: "Видеокарта AMD Radeon RX 7800 XT",
    category: "components",
    subcategory: "graphics-cards",
    brand: "ASUS",
    model: "DUAL-RX7800XT-O16G",
    sku: "AS-RX7800XT-001",
    price: 64990,
    oldPrice: 69990,
    discount: 7,
    cashback: 3250,
    stock: 8,
    rating: 4.9,
    reviewCount: 17,
    description:
      "Видеокарта ASUS DUAL-RX7800XT-O16G на базе AMD Radeon RX 7800 XT с 16 ГБ памяти GDDR6. Оснащена эффективной системой охлаждения с двумя вентиляторами Axial-tech, технологией 0dB для бесшумной работы при низких нагрузках и прочным металлическим каркасом для защиты от изгибов. Поддерживает технологии AMD FidelityFX Super Resolution, AMD Radeon Anti-Lag и AMD Radeon Boost.",
    shortDescription: "Мощная игровая видеокарта с 16 ГБ памяти GDDR6",
    specifications: [
      { name: "Графический процессор", value: "AMD Radeon RX 7800 XT" },
      { name: "Объем памяти", value: "16 ГБ GDDR6" },
      { name: "Разрядность шины памяти", value: "256 бит" },
      { name: "Частота графического процессора", value: "до 2430 МГц" },
      { name: "Частота памяти", value: "19.5 Гбит/с" },
      { name: "Интерфейс", value: "PCI-E 4.0" },
      { name: "Разъемы", value: "1x HDMI 2.1, 3x DisplayPort 2.1" },
      { name: "Рекомендуемая мощность БП", value: "750 Вт" },
      { name: "Система охлаждения", value: "Двухвентиляторная Axial-tech" },
    ],
    images: [
      {
        id: "2-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS DUAL-RX7800XT-O16G - вид сверху",
        isPrimary: true,
      },
      {
        id: "2-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS DUAL-RX7800XT-O16G - вид сбоку",
        isPrimary: false,
      },
      {
        id: "2-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS DUAL-RX7800XT-O16G - разъемы",
        isPrimary: false,
      },
    ],
    features: [
      "Высокая производительность в играх 1440p и 4K",
      "Технология AMD FidelityFX Super Resolution",
      "Система охлаждения с двумя вентиляторами Axial-tech",
      "Технология 0dB для бесшумной работы",
      "Прочный металлический каркас",
    ],
    isBestseller: true,
  },
  {
    id: "3",
    slug: "samsung-galaxy-s23-ultra",
    name: "Смартфон Samsung Galaxy S23 Ultra",
    category: "smartphones",
    subcategory: "android-smartphones",
    brand: "Samsung",
    model: "Galaxy S23 Ultra",
    sku: "SM-S918B",
    price: 99990,
    oldPrice: 109990,
    discount: 9,
    cashback: 5000,
    stock: 12,
    rating: 4.8,
    reviewCount: 42,
    description:
      "Samsung Galaxy S23 Ultra - флагманский смартфон с 6.8-дюймовым Dynamic AMOLED 2X дисплеем с разрешением QHD+ и частотой обновления 120 Гц. Оснащен процессором Snapdragon 8 Gen 2, 12 ГБ оперативной памяти и 256 ГБ встроенной памяти. Основная камера состоит из четырех модулей: 200 Мп (широкоугольный), 12 Мп (сверхширокоугольный), 10 Мп (телефото с 3x зумом) и 10 Мп (телефото с 10x зумом). Фронтальная камера - 12 Мп. Аккумулятор емкостью 5000 мАч с поддержкой быстрой зарядки 45 Вт и беспроводной зарядки 15 Вт.",
    shortDescription: "Флагманский смартфон с 200 Мп камерой и S Pen",
    specifications: [
      { name: "Дисплей", value: '6.8", Dynamic AMOLED 2X, 3088x1440, 120 Гц' },
      { name: "Процессор", value: "Snapdragon 8 Gen 2" },
      { name: "Оперативная память", value: "12 ГБ" },
      { name: "Встроенная память", value: "256 ГБ" },
      { name: "Основная камера", value: "200 Мп + 12 Мп + 10 Мп + 10 Мп" },
      { name: "Фронтальная камера", value: "12 Мп" },
      { name: "Аккумулятор", value: "5000 мАч" },
      { name: "Быстрая зарядка", value: "45 Вт" },
      { name: "Беспроводная зарядка", value: "15 Вт" },
      { name: "Защита от воды и пыли", value: "IP68" },
      { name: "Операционная система", value: "Android 13, One UI 5.1" },
    ],
    images: [
      {
        id: "3-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy S23 Ultra - вид спереди",
        isPrimary: true,
      },
      {
        id: "3-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy S23 Ultra - вид сзади",
        isPrimary: false,
      },
      {
        id: "3-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy S23 Ultra - камера",
        isPrimary: false,
      },
    ],
    features: [
      "200 Мп основная камера с продвинутыми возможностями ночной съемки",
      "Встроенный стилус S Pen",
      "Мощный процессор Snapdragon 8 Gen 2",
      'Яркий 6.8" Dynamic AMOLED 2X дисплей с частотой 120 Гц',
      "Аккумулятор 5000 мАч с быстрой зарядкой 45 Вт",
    ],
    isBestseller: true,
    isRecommended: true,
  },
  {
    id: "4",
    slug: "apple-iphone-15-pro-max",
    name: "Смартфон Apple iPhone 15 Pro Max",
    category: "smartphones",
    subcategory: "ios-smartphones",
    brand: "Apple",
    model: "iPhone 15 Pro Max",
    sku: "AP-IP15PM-256",
    price: 129990,
    oldPrice: 139990,
    discount: 7,
    cashback: 6500,
    stock: 10,
    rating: 4.9,
    reviewCount: 38,
    description:
      "Apple iPhone 15 Pro Max - флагманский смартфон с 6.7-дюймовым Super Retina XDR OLED дисплеем с технологией ProMotion и частотой обновления до 120 Гц. Оснащен процессором A17 Pro, 8 ГБ оперативной памяти и 256 ГБ встроенной памяти. Основная камера состоит из трех модулей: 48 Мп (широкоугольный), 12 Мп (сверхширокоугольный) и 12 Мп (телефото с 5x оптическим зумом). Фронтальная камера - 12 Мп с системой TrueDepth. Корпус выполнен из титана, что делает устройство легче и прочнее. Поддерживает технологию MagSafe для беспроводной зарядки и аксессуаров.",
    shortDescription:
      "Флагманский смартфон с титановым корпусом и процессором A17 Pro",
    specifications: [
      {
        name: "Дисплей",
        value: '6.7", Super Retina XDR OLED, 2796x1290, 120 Гц',
      },
      { name: "Процессор", value: "A17 Pro" },
      { name: "Оперативная память", value: "8 ГБ" },
      { name: "Встроенная память", value: "256 ГБ" },
      { name: "Основная камера", value: "48 Мп + 12 Мп + 12 Мп" },
      { name: "Фронтальная камера", value: "12 Мп" },
      { name: "Аккумулятор", value: "4422 мАч" },
      { name: "Быстрая зарядка", value: "27 Вт" },
      { name: "Беспроводная зарядка", value: "15 Вт (MagSafe)" },
      { name: "Защита от воды и пыли", value: "IP68" },
      { name: "Операционная система", value: "iOS 17" },
    ],
    images: [
      {
        id: "4-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPhone 15 Pro Max - вид спереди",
        isPrimary: true,
      },
      {
        id: "4-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPhone 15 Pro Max - вид сзади",
        isPrimary: false,
      },
      {
        id: "4-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPhone 15 Pro Max - камера",
        isPrimary: false,
      },
    ],
    features: [
      "Титановый корпус - легче и прочнее",
      "Мощный процессор A17 Pro с улучшенной графикой",
      "Профессиональная система камер с 48 Мп основным сенсором",
      "Дисплей Super Retina XDR с технологией ProMotion",
      "Поддержка технологии MagSafe",
    ],
    isNew: true,
    isBestseller: true,
  },
  {
    id: "5",
    slug: "sony-playstation-5-slim-digital",
    name: "Игровая приставка Sony PlayStation 5 Slim Digital Edition",
    category: "gaming",
    subcategory: "consoles",
    brand: "Sony",
    model: "PlayStation 5 Slim Digital Edition",
    sku: "PS5-SLIM-DE",
    price: 39990,
    oldPrice: 44990,
    discount: 11,
    cashback: 2000,
    stock: 7,
    rating: 4.8,
    reviewCount: 29,
    description:
      "Sony PlayStation 5 Slim Digital Edition - компактная версия популярной игровой консоли без дисковода. Оснащена процессором AMD Zen 2 с 8 ядрами и частотой 3.5 ГГц, графическим процессором AMD RDNA 2 с производительностью 10.3 TFLOPS, 16 ГБ оперативной памяти GDDR6 и SSD-накопителем на 825 ГБ с возможностью расширения. Поддерживает игры в разрешении 4K с частотой до 120 кадров в секунду, технологию трассировки лучей и 3D-аудио.",
    shortDescription:
      "Компактная игровая консоль нового поколения без дисковода",
    specifications: [
      { name: "Процессор", value: "AMD Zen 2, 8 ядер, 3.5 ГГц" },
      { name: "Графический процессор", value: "AMD RDNA 2, 10.3 TFLOPS" },
      { name: "Оперативная память", value: "16 ГБ GDDR6" },
      { name: "Накопитель", value: "825 ГБ SSD" },
      { name: "Оптический привод", value: "Отсутствует" },
      { name: "Разрешение", value: "До 4K при 120 Гц" },
      {
        name: "Особенности",
        value: "Трассировка лучей, 3D-аудио, тактильная обратная связь",
      },
      {
        name: "Интерфейсы",
        value: "HDMI 2.1, USB Type-A, USB Type-C, Ethernet",
      },
      { name: "Беспроводные технологии", value: "Wi-Fi 6, Bluetooth 5.1" },
    ],
    images: [
      {
        id: "5-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Sony PlayStation 5 Slim Digital Edition - вид спереди",
        isPrimary: true,
      },
      {
        id: "5-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Sony PlayStation 5 Slim Digital Edition - вид сбоку",
        isPrimary: false,
      },
      {
        id: "5-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Sony PlayStation 5 Slim Digital Edition с контроллером",
        isPrimary: false,
      },
    ],
    features: [
      "Компактный дизайн - на 30% меньше оригинальной PS5",
      "Высокая производительность для игр в 4K",
      "Сверхбыстрый SSD для мгновенной загрузки",
      "Инновационный контроллер DualSense с тактильной обратной связью",
      "Поддержка технологии трассировки лучей",
    ],
    isRecommended: true,
  },
  {
    id: "6",
    slug: "samsung-990-evo-plus-1tb",
    name: "SSD накопитель Samsung 990 EVO Plus 1TB",
    category: "components",
    subcategory: "storage",
    brand: "Samsung",
    model: "990 EVO Plus",
    sku: "MZ-V9P1T0BW",
    price: 9990,
    oldPrice: 12990,
    discount: 23,
    cashback: 500,
    stock: 25,
    rating: 4.7,
    reviewCount: 19,
    description:
      "Samsung 990 EVO Plus - высокопроизводительный SSD-накопитель формата M.2 NVMe с емкостью 1 ТБ. Обеспечивает скорость последовательного чтения до 7450 МБ/с и записи до 6900 МБ/с. Оснащен контроллером Samsung Elpis и памятью V-NAND 6-го поколения. Поддерживает интерфейс PCIe 4.0 x4 и протокол NVMe 1.4. Имеет высокую надежность с ресурсом записи 600 TBW и 5-летней гарантией производителя.",
    shortDescription: "Высокоскоростной SSD-накопитель M.2 NVMe емкостью 1 ТБ",
    specifications: [
      { name: "Форм-фактор", value: "M.2 2280" },
      { name: "Интерфейс", value: "PCIe 4.0 x4, NVMe 1.4" },
      { name: "Емкость", value: "1 ТБ" },
      { name: "Скорость чтения", value: "До 7450 МБ/с" },
      { name: "Скорость записи", value: "До 6900 МБ/с" },
      { name: "Контроллер", value: "Samsung Elpis" },
      { name: "Тип памяти", value: "Samsung V-NAND 6-го поколения" },
      { name: "Ресурс записи (TBW)", value: "600 ТБ" },
      { name: "Гарантия", value: "5 лет" },
    ],
    images: [
      {
        id: "6-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung 990 EVO Plus 1TB - вид сверху",
        isPrimary: true,
      },
      {
        id: "6-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung 990 EVO Plus 1TB - вид снизу",
        isPrimary: false,
      },
      {
        id: "6-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung 990 EVO Plus 1TB - упаковка",
        isPrimary: false,
      },
    ],
    features: [
      "Высокая скорость чтения до 7450 МБ/с",
      "Высокая скорость записи до 6900 МБ/с",
      "Поддержка PCIe 4.0 для максимальной производительности",
      "Низкое энергопотребление и тепловыделение",
      "Высокая надежность с ресурсом записи 600 TBW",
    ],
    isNew: true,
  },
  // Tablets
  {
    id: "7",
    slug: "apple-ipad-pro-m2-11",
    name: 'Планшет Apple iPad Pro M2 11"',
    category: "tablets",
    subcategory: "ios-tablets",
    brand: "Apple",
    model: "iPad Pro M2 11-inch",
    sku: "AP-IPADPRO-M2-11",
    price: 89990,
    oldPrice: 94990,
    discount: 5,
    cashback: 4500,
    stock: 9,
    rating: 4.9,
    reviewCount: 24,
    description:
      'Apple iPad Pro M2 11" - профессиональный планшет с 11-дюймовым Liquid Retina дисплеем с технологией ProMotion и частотой обновления до 120 Гц. Оснащен мощным процессором Apple M2 с 8-ядерным CPU и 10-ядерным GPU, 8 ГБ оперативной памяти и 256 ГБ встроенной памяти. Основная камера состоит из двух модулей: 12 Мп (широкоугольный) и 10 Мп (сверхширокоугольный), а также сканера LiDAR. Фронтальная камера - 12 Мп с технологией Center Stage. Поддерживает Apple Pencil 2-го поколения и Magic Keyboard.',
    shortDescription:
      "Профессиональный планшет с процессором Apple M2 и дисплеем Liquid Retina",
    specifications: [
      { name: "Дисплей", value: '11", Liquid Retina, 2388x1668, 120 Гц' },
      { name: "Процессор", value: "Apple M2, 8-ядерный CPU, 10-ядерный GPU" },
      { name: "Оперативная память", value: "8 ГБ" },
      { name: "Встроенная память", value: "256 ГБ" },
      { name: "Основная камера", value: "12 Мп + 10 Мп + LiDAR" },
      { name: "Фронтальная камера", value: "12 Мп с Center Stage" },
      { name: "Аккумулятор", value: "До 10 часов работы" },
      { name: "Разъем", value: "USB-C (Thunderbolt 4)" },
      { name: "Биометрия", value: "Face ID" },
      { name: "Операционная система", value: "iPadOS 16" },
    ],
    images: [
      {
        id: "7-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPad Pro M2 11-inch - вид спереди",
        isPrimary: true,
      },
      {
        id: "7-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPad Pro M2 11-inch - вид сзади",
        isPrimary: false,
      },
      {
        id: "7-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple iPad Pro M2 11-inch с Apple Pencil",
        isPrimary: false,
      },
    ],
    features: [
      "Мощный процессор Apple M2 для профессиональных задач",
      "Дисплей Liquid Retina с технологией ProMotion (120 Гц)",
      "Поддержка Apple Pencil 2-го поколения и Magic Keyboard",
      "Сканер LiDAR для расширенных возможностей AR",
      "Thunderbolt 4 для высокоскоростной передачи данных",
    ],
    isNew: true,
    isRecommended: true,
  },
  {
    id: "8",
    slug: "samsung-galaxy-tab-s9-ultra",
    name: "Планшет Samsung Galaxy Tab S9 Ultra",
    category: "tablets",
    subcategory: "android-tablets",
    brand: "Samsung",
    model: "Galaxy Tab S9 Ultra",
    sku: "SM-X910",
    price: 119990,
    oldPrice: 129990,
    discount: 8,
    cashback: 6000,
    stock: 5,
    rating: 4.8,
    reviewCount: 16,
    description:
      "Samsung Galaxy Tab S9 Ultra - флагманский планшет с огромным 14.6-дюймовым Dynamic AMOLED 2X дисплеем с разрешением 2960x1848 и частотой обновления 120 Гц. Оснащен мощным процессором Snapdragon 8 Gen 2, 12 ГБ оперативной памяти и 256 ГБ встроенной памяти с возможностью расширения до 1 ТБ с помощью microSD. Двойная основная камера: 13 Мп (основная) и 8 Мп (сверхширокоугольная). Двойная фронтальная камера: 12 Мп (широкоугольная) и 12 Мп (сверхширокоугольная). Аккумулятор емкостью 11200 мАч с поддержкой быстрой зарядки 45 Вт. Поставляется с S Pen в комплекте.",
    shortDescription:
      "Флагманский планшет с огромным 14.6-дюймовым дисплеем и S Pen",
    specifications: [
      { name: "Дисплей", value: '14.6", Dynamic AMOLED 2X, 2960x1848, 120 Гц' },
      { name: "Процессор", value: "Snapdragon 8 Gen 2" },
      { name: "Оперативная память", value: "12 ГБ" },
      { name: "Встроенная память", value: "256 ГБ" },
      { name: "Слот для карты памяти", value: "microSD до 1 ТБ" },
      { name: "Основная камера", value: "13 Мп + 8 Мп" },
      { name: "Фронтальная камера", value: "12 Мп + 12 Мп" },
      { name: "Аккумулятор", value: "11200 мАч" },
      { name: "Быстрая зарядка", value: "45 Вт" },
      { name: "Защита от воды и пыли", value: "IP68" },
      { name: "Операционная система", value: "Android 13, One UI 5.1" },
    ],
    images: [
      {
        id: "8-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy Tab S9 Ultra - вид спереди",
        isPrimary: true,
      },
      {
        id: "8-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy Tab S9 Ultra - вид сзади",
        isPrimary: false,
      },
      {
        id: "8-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Galaxy Tab S9 Ultra с S Pen",
        isPrimary: false,
      },
    ],
    features: [
      "Огромный 14.6-дюймовый Dynamic AMOLED 2X дисплей",
      "Мощный процессор Snapdragon 8 Gen 2",
      "S Pen в комплекте с улучшенной чувствительностью",
      "Защита от воды и пыли по стандарту IP68",
      "Четыре динамика с настройкой AKG и поддержкой Dolby Atmos",
    ],
    isBestseller: true,
  },
  // Laptops
  {
    id: "9",
    slug: "asus-rog-zephyrus-g16",
    name: "Ноутбук ASUS ROG Zephyrus G16",
    category: "laptops",
    subcategory: "gaming-laptops",
    brand: "ASUS",
    model: "ROG Zephyrus G16 GU605",
    sku: "GU605MV-NL044",
    price: 159990,
    oldPrice: 179990,
    discount: 11,
    cashback: 8000,
    stock: 7,
    rating: 4.8,
    reviewCount: 22,
    description:
      "ASUS ROG Zephyrus G16 - мощный игровой ноутбук с 16-дюймовым IPS-дисплеем с разрешением 2560x1600, частотой обновления 240 Гц и временем отклика 3 мс. Оснащен процессором Intel Core i9-13900H, видеокартой NVIDIA GeForce RTX 4070 с 8 ГБ GDDR6, 32 ГБ оперативной памяти DDR5 и SSD-накопителем на 1 ТБ PCIe 4.0. Система охлаждения ROG Intelligent Cooling с жидким металлом Thermal Grizzly и технологией 0dB Ambient Cooling. Аккумулятор емкостью 90 Вт·ч обеспечивает до 10 часов автономной работы.",
    shortDescription:
      "Мощный игровой ноутбук с RTX 4070 и процессором Intel Core i9",
    specifications: [
      { name: "Дисплей", value: '16", IPS, 2560x1600, 240 Гц, 3 мс' },
      { name: "Процессор", value: "Intel Core i9-13900H, 14 ядер, до 5.4 ГГц" },
      { name: "Видеокарта", value: "NVIDIA GeForce RTX 4070, 8 ГБ GDDR6" },
      { name: "Оперативная память", value: "32 ГБ DDR5-4800" },
      { name: "Накопитель", value: "1 ТБ SSD PCIe 4.0 NVMe" },
      { name: "Клавиатура", value: "RGB-подсветка, ход клавиш 1.7 мм" },
      { name: "Аккумулятор", value: "90 Вт·ч, до 10 часов работы" },
      {
        name: "Интерфейсы",
        value: "2x USB-C, 2x USB-A, HDMI 2.1, 3.5 мм аудио, RJ-45",
      },
      { name: "Беспроводные технологии", value: "Wi-Fi 6E, Bluetooth 5.3" },
      { name: "Операционная система", value: "Windows 11 Pro" },
    ],
    images: [
      {
        id: "9-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS ROG Zephyrus G16 - вид спереди",
        isPrimary: true,
      },
      {
        id: "9-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS ROG Zephyrus G16 - вид сбоку",
        isPrimary: false,
      },
      {
        id: "9-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "ASUS ROG Zephyrus G16 - клавиатура",
        isPrimary: false,
      },
    ],
    features: [
      "Мощная видеокарта NVIDIA GeForce RTX 4070",
      "Процессор Intel Core i9-13900H 14-го поколения",
      "Дисплей с частотой обновления 240 Гц и временем отклика 3 мс",
      "Система охлаждения ROG Intelligent Cooling с жидким металлом",
      "Долгое время автономной работы до 10 часов",
    ],
    isNew: true,
    isBestseller: true,
  },
  {
    id: "10",
    slug: "apple-macbook-pro-14-m3-pro",
    name: "Ноутбук Apple MacBook Pro 14 M3 Pro",
    category: "laptops",
    subcategory: "macbooks",
    brand: "Apple",
    model: "MacBook Pro 14 M3 Pro",
    sku: "MPHF3",
    price: 249990,
    oldPrice: 269990,
    discount: 7,
    cashback: 12500,
    stock: 6,
    rating: 4.9,
    reviewCount: 31,
    description:
      "Apple MacBook Pro 14 с чипом M3 Pro - профессиональный ноутбук с 14.2-дюймовым Liquid Retina XDR дисплеем с разрешением 3024x1964, яркостью до 1600 нит и технологией ProMotion с частотой обновления до 120 Гц. Оснащен процессором Apple M3 Pro с 12-ядерным CPU и 18-ядерным GPU, 18 ГБ объединенной памяти и SSD-накопителем на 512 ГБ. Система из шести динамиков с поддержкой пространственного аудио и технологией Dolby Atmos. Аккумулятор обеспечивает до 18 часов автономной работы.",
    shortDescription:
      "Профессиональный ноутбук с чипом Apple M3 Pro и дисплеем Liquid Retina XDR",
    specifications: [
      { name: "Дисплей", value: '14.2", Liquid Retina XDR, 3024x1964, 120 Гц' },
      {
        name: "Процессор",
        value: "Apple M3 Pro, 12-ядерный CPU, 18-ядерный GPU",
      },
      { name: "Оперативная память", value: "18 ГБ объединенной памяти" },
      { name: "Накопитель", value: "512 ГБ SSD" },
      { name: "Камера", value: "1080p FaceTime HD" },
      {
        name: "Аудио",
        value: "Система из 6 динамиков с поддержкой Dolby Atmos",
      },
      { name: "Аккумулятор", value: "До 18 часов работы" },
      {
        name: "Интерфейсы",
        value: "3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5 мм аудио",
      },
      { name: "Беспроводные технологии", value: "Wi-Fi 6E, Bluetooth 5.3" },
      { name: "Операционная система", value: "macOS Sonoma" },
    ],
    images: [
      {
        id: "10-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple MacBook Pro 14 M3 Pro - вид спереди",
        isPrimary: true,
      },
      {
        id: "10-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple MacBook Pro 14 M3 Pro - вид сбоку",
        isPrimary: false,
      },
      {
        id: "10-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Apple MacBook Pro 14 M3 Pro - клавиатура",
        isPrimary: false,
      },
    ],
    features: [
      "Мощный чип Apple M3 Pro для профессиональных задач",
      "Дисплей Liquid Retina XDR с технологией ProMotion",
      "Длительное время автономной работы до 18 часов",
      "Расширенные возможности подключения с Thunderbolt 4",
      "Система из шести динамиков с поддержкой Dolby Atmos",
    ],
    isNew: true,
    isRecommended: true,
  },
  // TVs
  {
    id: "11",
    slug: "lg-oled-c3-65",
    name: 'Телевизор LG OLED65C3 65"',
    category: "tvs",
    subcategory: "oled-tvs",
    brand: "LG",
    model: "OLED65C3",
    sku: "OLED65C3RLA",
    price: 149990,
    oldPrice: 179990,
    discount: 17,
    cashback: 7500,
    stock: 8,
    rating: 4.9,
    reviewCount: 36,
    description:
      "LG OLED65C3 - премиальный OLED-телевизор с 65-дюймовым экраном, разрешением 4K Ultra HD (3840x2160) и технологией самоподсвечивающихся пикселей. Оснащен процессором α9 Gen6 AI 4K, поддерживает HDR10, Dolby Vision, Dolby Atmos и имеет частоту обновления 120 Гц. Операционная система webOS 23 с поддержкой всех популярных стриминговых сервисов. Технология OLED evo обеспечивает повышенную яркость и улучшенную цветопередачу. Идеально подходит для просмотра фильмов, спортивных трансляций и игр благодаря низкой задержке ввода и поддержке NVIDIA G-Sync и AMD FreeSync Premium.",
    shortDescription:
      "Премиальный OLED-телевизор с технологией OLED evo и процессором α9 Gen6 AI",
    specifications: [
      { name: "Диагональ", value: '65" (165 см)' },
      { name: "Разрешение", value: "3840x2160 (4K UHD)" },
      { name: "Тип матрицы", value: "OLED evo" },
      { name: "Процессор", value: "α9 Gen6 AI 4K" },
      { name: "Частота обновления", value: "120 Гц" },
      { name: "HDR", value: "HDR10, Dolby Vision, HLG" },
      { name: "Звук", value: "2.2 канала, 40 Вт, Dolby Atmos" },
      { name: "Smart TV", value: "webOS 23" },
      {
        name: "Интерфейсы",
        value: "4x HDMI 2.1, 3x USB, Ethernet, Wi-Fi, Bluetooth",
      },
      {
        name: "Игровые функции",
        value: "NVIDIA G-Sync, AMD FreeSync Premium, VRR, ALLM",
      },
    ],
    images: [
      {
        id: "11-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG OLED65C3 - вид спереди",
        isPrimary: true,
      },
      {
        id: "11-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG OLED65C3 - вид сбоку",
        isPrimary: false,
      },
      {
        id: "11-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG OLED65C3 - интерфейсы",
        isPrimary: false,
      },
    ],
    features: [
      "Технология OLED evo для повышенной яркости и улучшенной цветопередачи",
      "Процессор α9 Gen6 AI с искусственным интеллектом",
      "Поддержка Dolby Vision и Dolby Atmos",
      "Игровые функции NVIDIA G-Sync и AMD FreeSync Premium",
      "Операционная система webOS 23 с голосовым управлением",
    ],
    isBestseller: true,
    isRecommended: true,
  },
  {
    id: "12",
    slug: "samsung-neo-qled-qn90c-55",
    name: 'Телевизор Samsung Neo QLED QE55QN90C 55"',
    category: "tvs",
    subcategory: "qled-tvs",
    brand: "Samsung",
    model: "QE55QN90C",
    sku: "QE55QN90CAUXRU",
    price: 119990,
    oldPrice: 139990,
    discount: 14,
    cashback: 6000,
    stock: 11,
    rating: 4.8,
    reviewCount: 29,
    description:
      "Samsung Neo QLED QE55QN90C - премиальный телевизор с 55-дюймовым экраном, технологией Quantum Mini LED и разрешением 4K Ultra HD (3840x2160). Оснащен процессором Neural Quantum 4K, поддерживает HDR10+, имеет частоту обновления 144 Гц и технологию локального затемнения Quantum Matrix. Операционная система Tizen с поддержкой всех популярных стриминговых сервисов. Технология Anti-Reflection минимизирует отражения и блики на экране. Звуковая система Object Tracking Sound+ (OTS+) с мощностью 60 Вт обеспечивает объемное звучание.",
    shortDescription:
      "Премиальный Neo QLED телевизор с технологией Quantum Mini LED и частотой 144 Гц",
    specifications: [
      { name: "Диагональ", value: '55" (140 см)' },
      { name: "Разрешение", value: "3840x2160 (4K UHD)" },
      { name: "Тип матрицы", value: "Neo QLED (Quantum Mini LED)" },
      { name: "Процессор", value: "Neural Quantum 4K" },
      { name: "Частота обновления", value: "144 Гц" },
      { name: "HDR", value: "HDR10+, HLG" },
      { name: "Звук", value: "OTS+, 4.2.2 канала, 60 Вт" },
      { name: "Smart TV", value: "Tizen" },
      {
        name: "Интерфейсы",
        value: "4x HDMI 2.1, 2x USB, Ethernet, Wi-Fi, Bluetooth",
      },
      {
        name: "Игровые функции",
        value: "Game Bar, VRR, ALLM, FreeSync Premium Pro",
      },
    ],
    images: [
      {
        id: "12-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Neo QLED QE55QN90C - вид спереди",
        isPrimary: true,
      },
      {
        id: "12-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Neo QLED QE55QN90C - вид сбоку",
        isPrimary: false,
      },
      {
        id: "12-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Samsung Neo QLED QE55QN90C - интерфейсы",
        isPrimary: false,
      },
    ],
    features: [
      "Технология Quantum Mini LED для глубокого черного и яркого изображения",
      "Частота обновления 144 Гц для плавного движения",
      "Технология Anti-Reflection для минимизации бликов",
      "Звуковая система Object Tracking Sound+ (OTS+)",
      "Игровая панель Game Bar с настройками для геймеров",
    ],
    isNew: true,
  },
  // Peripherals
  {
    id: "13",
    slug: "logitech-mx-master-3s",
    name: "Мышь Logitech MX Master 3S",
    category: "peripherals",
    subcategory: "mice",
    brand: "Logitech",
    model: "MX Master 3S",
    sku: "910-006559",
    price: 9990,
    oldPrice: 11990,
    discount: 17,
    cashback: 500,
    stock: 22,
    rating: 4.9,
    reviewCount: 47,
    description:
      "Logitech MX Master 3S - премиальная беспроводная мышь с эргономичным дизайном для продолжительной работы. Оснащена высокоточным сенсором с разрешением 8000 DPI, который работает даже на стеклянных поверхностях. Технология Quiet Clicks обеспечивает тихие клики, которые на 90% тише предыдущей модели. Электромагнитное колесо прокрутки MagSpeed позволяет прокручивать до 1000 строк в секунду. Поддерживает подключение до 3 устройств через Bluetooth или USB-приемник Logi Bolt. Аккумулятор обеспечивает до 70 дней работы от одной зарядки, а быстрая зарядка за 1 минуту дает 3 часа использования.",
    shortDescription:
      "Премиальная беспроводная мышь с тихими кликами и сенсором 8000 DPI",
    specifications: [
      { name: "Тип", value: "Беспроводная" },
      { name: "Сенсор", value: "Оптический, 8000 DPI" },
      { name: "Количество кнопок", value: "7" },
      { name: "Колесо прокрутки", value: "MagSpeed, электромагнитное" },
      { name: "Подключение", value: "Bluetooth, USB-приемник Logi Bolt" },
      { name: "Количество устройств", value: "До 3" },
      { name: "Аккумулятор", value: "До 70 дней работы" },
      { name: "Быстрая зарядка", value: "1 минута = 3 часа работы" },
      { name: "Совместимость", value: "Windows, macOS, Linux, iPadOS" },
      {
        name: "Особенности",
        value: "Технология Quiet Clicks, работа на стекле",
      },
    ],
    images: [
      {
        id: "13-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Logitech MX Master 3S - вид сверху",
        isPrimary: true,
      },
      {
        id: "13-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Logitech MX Master 3S - вид сбоку",
        isPrimary: false,
      },
      {
        id: "13-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Logitech MX Master 3S - в руке",
        isPrimary: false,
      },
    ],
    features: [
      "Тихие клики с технологией Quiet Clicks",
      "Высокоточный сенсор 8000 DPI с работой на стекле",
      "Электромагнитное колесо прокрутки MagSpeed",
      "Подключение до 3 устройств",
      "Длительное время работы до 70 дней",
    ],
    isNew: true,
    isRecommended: true,
  },
  {
    id: "14",
    slug: "keychron-q1-pro",
    name: "Клавиатура Keychron Q1 Pro",
    category: "peripherals",
    subcategory: "keyboards",
    brand: "Keychron",
    model: "Q1 Pro",
    sku: "Q1P-ANSI-RGB-RED",
    price: 14990,
    oldPrice: 16990,
    discount: 12,
    cashback: 750,
    stock: 9,
    rating: 4.8,
    reviewCount: 23,
    description:
      "Keychron Q1 Pro - премиальная механическая клавиатура формата 75% с алюминиевым корпусом, полностью настраиваемая и беспроводная. Оснащена переключателями Gateron G Pro Red (линейные), горячей заменой переключателей, RGB-подсветкой с южным расположением светодиодов и двухслойными прокладками для улучшения звука при печати. Поддерживает подключение через Bluetooth 5.1 к трем устройствам, USB Type-C и имеет аккумулятор на 4000 мАч. Совместима с Windows, macOS, Linux и iOS с возможностью переключения между режимами. Поддерживает QMK/VIA для полной настройки раскладки.",
    shortDescription:
      "Премиальная беспроводная механическая клавиатура формата 75% с алюминиевым корпусом",
    specifications: [
      { name: "Тип", value: "Механическая" },
      { name: "Формат", value: "75%" },
      { name: "Переключатели", value: "Gateron G Pro Red (линейные)" },
      { name: "Корпус", value: "Алюминиевый, цельный" },
      { name: "Подсветка", value: "RGB, южное расположение" },
      { name: "Подключение", value: "Bluetooth 5.1, USB Type-C" },
      { name: "Количество устройств", value: "До 3 по Bluetooth" },
      { name: "Аккумулятор", value: "4000 мАч" },
      { name: "Время работы", value: "До 300 часов без подсветки" },
      { name: "Программирование", value: "QMK/VIA" },
      { name: "Совместимость", value: "Windows, macOS, Linux, iOS" },
    ],
    images: [
      {
        id: "14-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Keychron Q1 Pro - вид сверху",
        isPrimary: true,
      },
      {
        id: "14-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Keychron Q1 Pro - вид сбоку",
        isPrimary: false,
      },
      {
        id: "14-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Keychron Q1 Pro - подсветка",
        isPrimary: false,
      },
    ],
    features: [
      "Полностью алюминиевый корпус с двойной прокладкой",
      "Горячая замена переключателей",
      "Беспроводное подключение к трем устройствам",
      "Полная настройка через QMK/VIA",
      "Совместимость с Windows и macOS",
    ],
    isNew: true,
  },
  // Home Appliances
  {
    id: "15",
    slug: "dyson-v15-detect-absolute",
    name: "Пылесос Dyson V15 Detect Absolute",
    category: "appliances",
    subcategory: "vacuum-cleaners",
    brand: "Dyson",
    model: "V15 Detect Absolute",
    sku: "371107-01",
    price: 59990,
    oldPrice: 69990,
    discount: 14,
    cashback: 3000,
    stock: 7,
    rating: 4.9,
    reviewCount: 34,
    description:
      "Dyson V15 Detect Absolute - беспроводной пылесос с технологией лазерного обнаружения пыли и грязи. Оснащен мощным цифровым двигателем Dyson Hyperdymium, который создает мощность всасывания до 240 AW, и системой фильтрации HEPA, улавливающей 99,97% частиц размером до 0,3 микрона. Интеллектуальный датчик пыли автоматически регулирует мощность всасывания в зависимости от количества обнаруженной пыли. ЖК-экран отображает информацию о режиме работы, оставшемся времени работы и количестве собранных частиц. Аккумулятор обеспечивает до 60 минут работы без подзарядки.",
    shortDescription:
      "Беспроводной пылесос с лазерным обнаружением пыли и интеллектуальным датчиком",
    specifications: [
      { name: "Тип", value: "Беспроводной, вертикальный" },
      { name: "Мощность всасывания", value: "До 240 AW" },
      { name: "Фильтрация", value: "HEPA, 5-ступенчатая" },
      { name: "Объем контейнера", value: "0.76 л" },
      { name: "Время работы", value: "До 60 минут" },
      { name: "Время зарядки", value: "4.5 часа" },
      { name: "Вес", value: "3.1 кг" },
      { name: "Уровень шума", value: "До 82 дБ" },
      { name: "Насадки в комплекте", value: "6 шт." },
      {
        name: "Особенности",
        value: "Лазерное обнаружение пыли, интеллектуальный датчик, ЖК-экран",
      },
    ],
    images: [
      {
        id: "15-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Dyson V15 Detect Absolute - общий вид",
        isPrimary: true,
      },
      {
        id: "15-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Dyson V15 Detect Absolute - насадка с лазером",
        isPrimary: false,
      },
      {
        id: "15-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "Dyson V15 Detect Absolute - ЖК-экран",
        isPrimary: false,
      },
    ],
    features: [
      "Лазерное обнаружение невидимой пыли",
      "Интеллектуальный датчик пыли с автоматической регулировкой мощности",
      "Мощный цифровой двигатель Dyson Hyperdymium",
      "ЖК-экран с отображением статистики уборки",
      "Система фильтрации HEPA для чистого воздуха",
    ],
    isNew: true,
    isRecommended: true,
  },
  {
    id: "16",
    slug: "lg-f4v5vs9b",
    name: "Стиральная машина LG F4V5VS9B",
    category: "appliances",
    subcategory: "washing-machines",
    brand: "LG",
    model: "F4V5VS9B",
    sku: "F4V5VS9B",
    price: 49990,
    oldPrice: 59990,
    discount: 17,
    cashback: 2500,
    stock: 5,
    rating: 4.7,
    reviewCount: 28,
    description:
      "LG F4V5VS9B - стиральная машина с фронтальной загрузкой, вместимостью 9 кг и технологией AI DD (искусственный интеллект для определения типа ткани). Оснащена инверторным мотором Direct Drive с 10-летней гарантией, функцией пара Steam для удаления аллергенов и разглаживания складок, и технологией TurboWash 360° для быстрой и эффективной стирки за 39 минут. Имеет 14 программ стирки, включая специальные режимы для разных типов тканей. Класс энергоэффективности A+++ (-30%), уровень шума при стирке 51 дБ, при отжиме 73 дБ. Максимальная скорость отжима 1400 об/мин.",
    shortDescription:
      "  (-30%), уровень шума при стирке 51 дБ, при отжиме 73 дБ. Максимальная скорость отжима 1400 об/мин.",
    shortDescription:
      "Стиральная машина с искусственным интеллектом AI DD и функцией пара Steam",
    specifications: [
      { name: "Тип загрузки", value: "Фронтальная" },
      { name: "Максимальная загрузка", value: "9 кг" },
      { name: "Максимальная скорость отжима", value: "1400 об/мин" },
      { name: "Класс энергопотребления", value: "A+++ (-30%)" },
      { name: "Мотор", value: "Инверторный Direct Drive" },
      { name: "Количество программ", value: "14" },
      { name: "Технологии", value: "AI DD, Steam, TurboWash 360°" },
      { name: "Уровень шума при стирке", value: "51 дБ" },
      { name: "Уровень шума при отжиме", value: "73 дБ" },
      { name: "Габариты (ВxШxГ)", value: "85x60x56.5 см" },
    ],
    images: [
      {
        id: "16-1",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG F4V5VS9B - вид спереди",
        isPrimary: true,
      },
      {
        id: "16-2",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG F4V5VS9B - панель управления",
        isPrimary: false,
      },
      {
        id: "16-3",
        url: "/placeholder.svg?height=300&width=300",
        alt: "LG F4V5VS9B - барабан",
        isPrimary: false,
      },
    ],
    features: [
      "Технология AI DD для определения типа ткани",
      "Функция пара Steam для удаления аллергенов",
      "Технология TurboWash 360° для быстрой стирки",
      "Инверторный мотор Direct Drive с 10-летней гарантией",
      "Управление со смартфона через приложение LG ThinQ",
    ],
    isBestseller: true,
  },
];

export const categoryNames: Record<string, string> = {
  smartphones: "Смартфоны и часы",
  tablets: "Планшеты",
  laptops: "Ноутбуки",
  components: "Комплектующие",
  monitors: "Мониторы",
  tvs: "Телевизоры",
  peripherals: "Периферия",
  gaming: "Игры и консоли",
  appliances: "Бытовая техника",
}

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((product) => product.category === category)
}

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((product) => product.slug === slug)
}

export const getRelatedProducts = (product: Product, limit = 4): Product[] => {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit)
}

export const getRecommendedProducts = (limit = 4): Product[] => {
  return products.filter((p) => p.isRecommended).slice(0, limit)
}

export const getBestsellers = (limit = 4): Product[] => {
  return products.filter((p) => p.isBestseller).slice(0, limit)
}

export const getNewProducts = (limit = 4): Product[] => {
  return products.filter((p) => p.isNew).slice(0, limit)
}
